[package]
name = "threshold_crypto"
version = "0.1.0"
authors = ["Andreas Fackler <AndreasFackler@gmx.de>",
           "Peter van Nostrand <jnz@riseup.net>"]
description = "Pairing threshold cryptography"
license = "LGPL-3.0"
repository = "https://github.com/poanetwork/threshold_crypto"
readme = "https://github.com/poanetwork/threshold_crypto/blob/master/README.md"
keywords = ["pairing", "threshold"]
categories = ["cryptography"]

[dependencies]
byteorder = "1.2.3"
errno = "0.2.4"
failure = "0.1"
init_with = "1.1.0"
lazy_static = "1.1.0"
log = "0.4.1"
memsec = "0.5.4"
pairing = { version = "0.14.2", features = ["u128-support"] }
rand = "0.4.2"
rand_derive = "0.3.1"
serde = "1.0.55"
serde_derive = "1.0.55"
tiny-keccak = "1.4"

[dev-dependencies]
bincode = "1.0.0"
