[package]
name = "threshold_crypto"
# REMINDER: Update version in `README.md` when incrementing:
version = "0.1.0"
authors = ["Vladimir Komendantskiy <komendantsky@gmail.com>",
           "Andreas Fackler <AndreasFackler@gmx.de>",
           "Peter van Nostrand <jnz@riseup.net>",
           "Andrew Gross <andogro@gmail.com>",
           "Nick Sanders <nsan1129@gmail.com>",
           "Marc Brinkmann <git@marcbrinkmann.de>"]
description = "Pairing threshold cryptography"
license = "MIT/Apache-2.0"
repository = "https://github.com/poanetwork/threshold_crypto"
readme = "README.md"
keywords = ["pairing", "threshold"]
categories = ["cryptography"]

[dependencies]
byteorder = "1.2.3"
errno = "0.2.4"
failure = "0.1"
init_with = "1.1.0"
lazy_static = "1.1.0"
log = "0.4.1"
memsec = "0.5.4"
pairing = { version = "0.14.2", features = ["u128-support"] }
rand = "0.4.2"
rand_derive = "0.3.1"
serde = "1.0.55"
serde_derive = "1.0.55"
tiny-keccak = "1.4"
ff = { version = "0.4.0", optional = true }

[dev-dependencies]
bincode = "1.0.0"
criterion = "0.2"
rand = "0.4.2"
serde_derive = "1.0.55"

[[bench]]
name = "bench"
harness = false

[features]
use-insecure-test-only-mock-crypto = ["ff"]
